<?php

namespace Database\Seeders;

use App\Models\Content;
use Illuminate\Database\Seeder;

class ContentTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Content::create(['title' => 'Header', 'slug' => 'header', 'description' => '', 'content' => '[ { "links": [ { "label": "", "type": "internal", "url": "{\"path\":\"home\",\"label\":\"Accueil\"}" }, { "label": "Blog", "type": "internal", "url": "{\"path\":\"blog.index\",\"label\":\"Blog\"}" } ], "id": "header", "padding": 1, "animate": false, "backgroundColor": "var(--color-light)", "backgroundDesktop": "", "backgroundMobile": "", "titleColor": "var(--color-dark)", "textColor": "var(--color-dark)", "titleFontSize": 1, "fontSize": 1, "backgroundSize": "", "backgroundRepeat": "", "backgroundXPosition": "", "backgroundYPosition": "", "_name": "header" } ]', 'online' => '1', 'type' => 'header', 'user_id' => '1']);
        Content::create(['title' => 'Footer', 'slug' => 'footer', 'description' => '', 'content' => '[ { "credit": "<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>", "links": [ { "label": "", "type": "internal", "url": "{\"path\":\"page.show\",\"label\":\"Mentions légales\",\"slug\":\"mentions-legales\"}" } ], "id": "", "padding": 2, "animate": false, "backgroundColor": "var(--contrast)", "backgroundDesktop": "", "backgroundMobile": "", "titleColor": "var(--background)", "textColor": "var(--background)", "titleFontSize": 2, "fontSize": 1, "backgroundSize": "", "backgroundRepeat": "", "backgroundXPosition": "", "backgroundYPosition": "", "_name": "footer-credit" } ]', 'online' => '1', 'type' => 'footer', 'user_id' => '1']);
        Content::create(['title' => 'Home', 'slug' => 'home', 'description' => '', 'content' => '[ { "title": "Lorem ipsum dolor sit amet", "titleAlign": "left", "content": "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eum impedit laborum mollitia similique suscipit voluptatum.", "buttons": [], "id": "", "padding": 5, "animate": false, "backgroundColor": "", "backgroundDesktop": "", "backgroundMobile": "", "titleColor": "var(--contrast)", "textColor": "var(--color-dark)", "titleFontSize": 2, "fontSize": 1, "backgroundSize": "", "backgroundRepeat": "", "backgroundXPosition": "", "backgroundYPosition": "", "_name": "hero" }, { "title": "Lorem ipsum dolor sit amet", "titleAlign": "left", "content": "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eum impedit laborum mollitia similique suscipit voluptatum.", "buttons": [], "id": "", "padding": 5, "animate": false, "backgroundColor": "", "backgroundDesktop": "", "backgroundMobile": "", "titleColor": "var(--contrast)", "textColor": "var(--color-dark)", "titleFontSize": 2, "fontSize": 1, "backgroundSize": "", "backgroundRepeat": "", "backgroundXPosition": "", "backgroundYPosition": "", "_name": "hero" }, { "title": "Lorem ipsum dolor sit amet", "titleAlign": "left", "content": "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eum impedit laborum mollitia similique suscipit voluptatum.", "buttons": [], "id": "", "padding": 5, "animate": false, "backgroundColor": "", "backgroundDesktop": "", "backgroundMobile": "", "titleColor": "var(--contrast)", "textColor": "var(--color-dark)", "titleFontSize": 2, "fontSize": 1, "backgroundSize": "", "backgroundRepeat": "", "backgroundXPosition": "", "backgroundYPosition": "", "_name": "hero" }, { "title": "Lorem ipsum dolor sit amet", "titleAlign": "left", "content": "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eum impedit laborum mollitia similique suscipit voluptatum.", "buttons": [], "id": "", "padding": 5, "animate": false, "backgroundColor": "", "backgroundDesktop": "", "backgroundMobile": "", "titleColor": "var(--contrast)", "textColor": "var(--color-dark)", "titleFontSize": 2, "fontSize": 1, "backgroundSize": "", "backgroundRepeat": "", "backgroundXPosition": "", "backgroundYPosition": "", "_name": "hero" } ]', 'online' => '1', 'type' => 'page', 'user_id' => '1']);
        Content::create(['title' => 'Mentions Légales', 'slug' => 'mentions-legales', 'description' => '', 'content' => '[ { "title": "Lorem ipsum dolor sit amet", "titleAlign": "left", "content": "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eum impedit laborum mollitia similique suscipit voluptatum.", "buttons": [], "id": "", "padding": 5, "animate": false, "backgroundColor": "", "backgroundDesktop": "", "backgroundMobile": "", "titleColor": "var(--contrast)", "textColor": "var(--color-dark)", "titleFontSize": 2, "fontSize": 1, "backgroundSize": "", "backgroundRepeat": "", "backgroundXPosition": "", "backgroundYPosition": "", "_name": "hero" }, { "title": "Lorem ipsum dolor sit amet", "titleAlign": "left", "content": "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eum impedit laborum mollitia similique suscipit voluptatum.", "buttons": [], "id": "", "padding": 5, "animate": false, "backgroundColor": "", "backgroundDesktop": "", "backgroundMobile": "", "titleColor": "var(--contrast)", "textColor": "var(--color-dark)", "titleFontSize": 2, "fontSize": 1, "backgroundSize": "", "backgroundRepeat": "", "backgroundXPosition": "", "backgroundYPosition": "", "_name": "hero" }, { "title": "Lorem ipsum dolor sit amet", "titleAlign": "left", "content": "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eum impedit laborum mollitia similique suscipit voluptatum.", "buttons": [], "id": "", "padding": 5, "animate": false, "backgroundColor": "", "backgroundDesktop": "", "backgroundMobile": "", "titleColor": "var(--contrast)", "textColor": "var(--color-dark)", "titleFontSize": 2, "fontSize": 1, "backgroundSize": "", "backgroundRepeat": "", "backgroundXPosition": "", "backgroundYPosition": "", "_name": "hero" }, { "title": "Lorem ipsum dolor sit amet", "titleAlign": "left", "content": "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eum impedit laborum mollitia similique suscipit voluptatum.", "buttons": [], "id": "", "padding": 5, "animate": false, "backgroundColor": "", "backgroundDesktop": "", "backgroundMobile": "", "titleColor": "var(--contrast)", "textColor": "var(--color-dark)", "titleFontSize": 2, "fontSize": 1, "backgroundSize": "", "backgroundRepeat": "", "backgroundXPosition": "", "backgroundYPosition": "", "_name": "hero" } ]', 'online' => '1', 'type' => 'page', 'user_id' => '1']);
    }
}
