version: '3.3'
services:
    db:
        restart: unless-stopped
        image: mariadb:10.9.4
        ports:
            - 3306:3306 # On expose le port pour pouvoir inspecter la base pendant la phase de développement
        environment:
            MARIADB_ROOT_PASSWORD: root
            MARIADB_PASSWORD: user
            MARIADB_USER: user
            MYSQL_DATABASE: cms
        networks:
            - web
        volumes:
            - db-data:/var/lib/mariadb/data
            - ./var:/var/www/var
    mailhog:
        image: mailhog/mailhog
        networks:
            - web
        ports:
            - "1025:1025"
            - "8025:8025"
    php:
        restart: unless-stopped
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8082:8082"
        volumes:
            - .:/var/www/html
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.php.rule=Host(`cms.localhost`)"
            - "traefik.http.routers.php.entrypoints=https"
            - "traefik.http.routers.php.tls=true"
        depends_on:
            - db
        networks:
            - web
volumes:
    db-data:
        driver: local

networks:
    web:
        external: true
