version: '3.3'
services:
    db:
        restart: unless-stopped
        image: mariadb:10.9.4
        ports:
            - 3306:3306 # On expose le port pour pouvoir inspecter la base pendant la phase de développement
        environment:
            MARIADB_ROOT_PASSWORD: root
            MARIADB_PASSWORD: user
            MARIADB_USER: user
            MYSQL_DATABASE: cms
        volumes:
            - db-data:/var/lib/mariadb/data
            - ./var:/var/www/var
    web:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - .:/var/www:delegated
            - ./site.conf:/etc/nginx/conf.d/default.conf
        links:
            - php

    mailhog:
        image: mailhog/mailhog
        ports:
            - "1025:1025"
            - "8025:8025"
    php:
        user: '${USER_ID}:${GROUP_ID}'
        restart: unless-stopped
        image: grafikart/php:php8.1-1
        build:
            context: ./tools/docker/php
        volumes:
            - .:/var/www:delegated
        depends_on:
            - db
        environment:
            PHP_IDE_CONFIG: serverName=aymericlhomme
            APP_ENV: dev
            MAILER_DSN: smtp://contact@aymericlhomme.fr:*8*PR\A(zYy@nirrti.o2switch.net:465
            DATABASE_URL: mysql://user:user@db:3306/cms
            MESSENGER_TRANSPORT_DSN: doctrine://default?queue_name=async
            SCOUT_DRIVER: meilisearch
            MEILISEARCH_HOST: https://ms-633f85766c60-2346.nyc.meilisearch.io
            MEILISEARCH_KEY: 93200fbddce261de90d120763ead41851889d516
    node:
        user: '${USER_ID}:${GROUP_ID}'
        build:
            context: ./tools/docker/node
        command: 'npm run dev --theme=${THEME}'
        working_dir: /usr/src/app
        volumes:
            - .:/usr/src/app
        ports:
            - 5173:5173
volumes:
    db-data:
        driver: local

networks:
    dev:
